name: Build SE02 Dev-Diary with LaTeX
on: 
  push:
    branches: [ master ]
    paths: 
    - 'SE02/**'
    - '.github/workflows/SE02.yml'

jobs:
  render_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: main.tex
          working_directory: SE02
      - name: Change filename
        run: cp SE02/main.pdf JohnMeyerhoffSE02Entwicklertagebuch.pdf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'SE02 Entwickler-Tagebuch'
          path: 'JohnMeyerhoffSE02Entwicklertagebuch.pdf'